# Generated by Django 5.2.8 on 2025-11-14 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='project',
            field=models.ForeignKey(default='31ddfef8691f4769be61167d1626633c', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='api.project'),
            preserve_default=False,
        ),
    ]
