# Generated by Django 5.2.8 on 2025-11-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatmessage_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
