# Generated by Django 5.2.8 on 2025-11-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_column_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
