# Generated by Django 5.2.8 on 2025-12-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='folder',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
